language: cpp
sudo: required
dist: trusty

before_install:
#  - sudo apt-get remove cmake cmake-data --yes
#  - sudo add-apt-repository ppa:george-edison55/precise-backports --yes
  - sudo add-apt-repository ppa:terry.guo/gcc-arm-embedded --yes
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test --yes
#  - sudo add-apt-repository ppa:beineri/opt-qt551 --yes
  - sudo add-apt-repository 'deb http://llvm.org/apt/trusty/ llvm-toolchain-trusty main' --yes
  - wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key | sudo apt-key add -
  - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 1397BC53640DB551
  - sudo apt-get update -qq || echo foo

install:
  - sudo apt-get install -y xvfb lcov cmake cmake-data bc curl gcc-arm-none-eabi qt-latest g++-5 libxerces-c-dev xsdcxx libsdl1.2-dev libusb-1.0-0 libfox-1.6-dev libgtest-dev python-clang-3.9 libclang-3.9-dev python-qt4
  - export CXX="g++-5" CC="gcc-5"
  - wget --quiet http://firmware.ardupilot.org/Tools/Travis/gcc-avr_1%253a4.8-2.1_amd64.deb
  - wget --quiet http://firmware.ardupilot.org/Tools/Travis/libmpfr4_3.1.2-1_amd64.deb
  - wget --quiet http://firmware.ardupilot.org/Tools/Travis/avr-libc_1%253a1.8.0-4.1_all.deb
  - wget --quiet http://firmware.ardupilot.org/Tools/Travis/binutils-avr_2.23.1-2.1_amd64.deb
  - wget --quiet http://firmware.ardupilot.org/Tools/Travis/libmpc3_1.0.1-1ubuntu1_amd64.deb
  - sudo dpkg --install gcc-avr_1%3a4.8-2.1_amd64.deb avr-libc_1%3a1.8.0-4.1_all.deb libmpfr4_3.1.2-1_amd64.deb binutils-avr_2.23.1-2.1_amd64.deb libmpc3_1.0.1-1ubuntu1_amd64.deb

script:
  - ./radio/util/commit-tests.sh .
